spring.application.name=athlete-state-api
spring.datasource.url = jdbc:postgresql://localhost/athlete_state_db
spring.datasource.username = postgres
spring.datasource.password = ${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
